buildscript
        {
            repositories
                    {
                        google()
                        mavenCentral()
                    }
            dependencies
                    {
                        classpath 'com.android.tools.build:gradle:9.2.0'
                        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.20'
                    }
        }

tasks.register("clean", Delete)
{
    delete rootProject.layout.buildDirectory
}
