plugins
        {
            id('com.android.application')
        }

android
        {
            compileSdk 33
            defaultConfig
                    {
                        applicationId "com.wade.fsime"
                        minSdkVersion 26
                        targetSdkVersion 33
                        versionCode 231016
                        versionName "231016"
                    }
            buildTypes
                    {
                        release
                                {
                                    minifyEnabled true
                                    shrinkResources true
                                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                                }
                    }
            namespace 'com.wade.fsime'
            buildFeatures {
                buildConfig = true
            }
            compileOptions
                    {
                        sourceCompatibility JavaVersion.VERSION_17
                        targetCompatibility JavaVersion.VERSION_17
                    }
            androidResources
                    {
                        ignoreAssetsPattern '*.cmd:*.cmdr'
                    }
            lint {
                checkReleaseBuilds false
                abortOnError false
            }
        }

base {
    archivesName = "com.wade.fsime-${android.defaultConfig.versionName}"
}

dependencies
        {
            implementation('com.google.android.material:material:1.9.0')
            implementation('com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1')
            implementation 'androidx.preference:preference:1.2.1'
        }
