// This file is automatically generated by the build.py script. Do not edit!

/*
 * Copyright (C) 2008-2009 Mihai Preda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wade.libs.arity;

class VM {

static final byte
RESERVED = 0,
CONST = 1,
CALL = 2,
ADD = 3,
SUB = 4,
MUL = 5,
DIV = 6,
MOD = 7,
RND = 8,
UMIN = 9,
POWER = 10,
FACT = 11,
PERCENT = 12,
SQRT = 13,
CBRT = 14,
EXP = 15,
LN = 16,
SIN = 17,
COS = 18,
TAN = 19,
SEC = 20,
CSC = 21,
COT = 22,
ASIN = 23,
ACOS = 24,
ATAN = 25,
ASEC = 26,
ACSC = 27,
ACOT = 28,
SINH = 29,
COSH = 30,
TANH = 31,
SECH = 32,
CSCH = 33,
COTH = 34,
ASINH = 35,
ACOSH = 36,
ATANH = 37,
ASECH = 38,
ACSCH = 39,
ACOTH = 40,
ABS = 41,
FLOOR = 42,
CEIL = 43,
SIGN = 44,
MIN = 45,
MAX = 46,
GCD = 47,
COMB = 48,
PERM = 49,
LOAD0 = 50,
LOAD1 = 51,
LOAD2 = 52,
LOAD3 = 53,
LOAD4 = 54,
REAL = 55,
IMAG = 56;

static final String[] opcodeName = { "reserved", "const", "call", "add", "sub", "mul", "div", "mod", "rnd", "umin", "power", "fact", "percent", "sqrt", "cbrt", "exp", "ln", "sin", "cos", "tan", "sec", "csc", "cot", "asin", "acos", "atan", "asec", "acsc", "acot", "sinh", "cosh", "tanh", "sech", "csch", "coth", "asinh", "acosh", "atanh", "asech", "acsch", "acoth", "abs", "floor", "ceil", "sign", "min", "max", "gcd", "comb", "perm", "load0", "load1", "load2", "load3", "load4", "real", "imag"};
static final byte[] arity = { 0, 0, -1, 2, 2, 2, 2, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1};
static final byte[] builtins = { RND, SQRT, CBRT, SIN, COS, TAN, SEC, CSC, COT, ASIN, ACOS, ATAN, ASEC, ACSC, ACOT, SINH, COSH, TANH, SECH, CSCH, COTH, ASINH, ACOSH, ATANH, ASECH, ACSCH, ACOTH, EXP, LN, ABS, FLOOR, CEIL, SIGN, MIN, MAX, GCD, COMB, PERM, MOD, REAL, IMAG};
}
